# Bag of Words

In [1]:
import numpy as np 
import pandas as pd

In [2]:
df = pd.DataFrame({ 'text': ['people watch idiots','idiots watch idiots','people write comment','idiots write comment'],
     'output':[1,1,0,0]
    })

In [3]:
df

text  output
0   people watch idiots       1
1   idiots watch idiots       1
2  people write comment       0
3  idiots write comment       0

In [ ]:
# !pip install -U scikit-learn

In [4]:
from sklearn.feature_extraction.text import CountVectorizer

In [5]:
cv = CountVectorizer()

In [6]:
bow = cv.fit_transform(df['text'])

In [7]:
print(cv.vocabulary_)
# index number hai jo number hai 

{'people': 2, 'watch': 3, 'idiots': 1, 'write': 4, 'comment': 0}


In [8]:
df

text  output
0   people watch idiots       1
1   idiots watch idiots       1
2  people write comment       0
3  idiots write comment       0

In [9]:
print(bow[0].toarray())
# print(bow[1].toarray())

[[0 1 1 1 0]]


Yeah Abh Index By index bataraha hai whether it exist or not 


{'people': 2, 'watch': 3, 'idiots': 0, 'write': 4, 'comment': 1}

0 idiots,1 comment,2 people , 3 watch , 4 write  

[idiots, comment, people, watch, write]

In [ ]:
print(bow[0].toarray())
print(bow[1].toarray())

[[1 0 1 1 0]]
[[2 0 0 1 0]]


[[1 0 1 1 0]] : [idiots, comment, people, watch, write]

[[2 0 0 1 0]] : [idiots, comment, people, watch, write]

In [ ]:
cv.transform(['idiots watch and write comment of idiots']).toarray()

array([[2, 1, 0, 1, 1]], dtype=int64)

You can see above 
Out of Vocabulary ka problem nahi hoga Easily handle horaha hai,   
as and jo word hai vo training mai nahi hai  
btw and & of vosbh  Preprocessing mai hattjayenge yeah bss simple example hai 

In [ ]:
cv.transform(["people watch act dumb"]).toarray()

array([[0, 0, 1, 1, 0]], dtype=int64)

### Hyperparameter 

https://scikit-learn.org/stable/modules/generated/sklearn.feature_extraction.text.CountVectorizer.html

binary default mai false rehta    
but research has proved while doing    
sentiment analysis  binary = True  ache result dete hai 

max_feature 
