# TF - IDF 

### TF - Term Frequency. 
### IDF - Inverse Document Frequency.

In [1]:
import pandas as pd 
import numpy as np 

In [2]:
df = pd.DataFrame({ 'text': ['people watch idiots','idiots watch idiots','people write comment','idiots write comment'],
     'output':[1,1,0,0]
    })

In [3]:
df

text  output
0   people watch idiots       1
1   idiots watch idiots       1
2  people write comment       0
3  idiots write comment       0

In [4]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [5]:
tf_idf = TfidfVectorizer()

In [7]:
tf_idf.fit_transform(df['text']).toarray()

array([[0.        , 0.49681612, 0.61366674, 0.61366674, 0.        ],
       [0.        , 0.8508161 , 0.        , 0.52546357, 0.        ],
       [0.57735027, 0.        , 0.57735027, 0.        , 0.57735027],
       [0.61366674, 0.49681612, 0.        , 0.        , 0.61366674]])

In [11]:
print(tf_idf.idf_) # idf constant hota hai 
print(tf_idf.get_feature_names_out())

[1.51082562 1.22314355 1.51082562 1.51082562 1.51082562]
['comment' 'idiots' 'people' 'watch' 'write']


In [12]:
print(tf_idf.sc) # idf constant hota hai 
print(tf_idf.vocabulary_)

[1.51082562 1.22314355 1.51082562 1.51082562 1.51082562]
{'people': 2, 'watch': 3, 'idiots': 1, 'write': 4, 'comment': 0}
